object FormDev: TFormDev
  Left = 0
  Top = 0
  Caption = 'FormDev'
  ClientHeight = 609
  ClientWidth = 967
  Color = clBtnFace
  DoubleBuffered = True
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poOwnerFormCenter
  PixelsPerInch = 96
  TextHeight = 13
  object dxDockSite1: TdxDockSite
    Left = 0
    Top = 0
    Width = 185
    Height = 609
    Align = alLeft
    AutoSize = True
    ExplicitHeight = 140
    DockingType = 5
    OriginalWidth = 225
    OriginalHeight = 609
    object dxLayoutDockSite1: TdxLayoutDockSite
      Left = 0
      Top = 0
      Width = 185
      Height = 609
      ExplicitWidth = 300
      ExplicitHeight = 200
      DockingType = 0
      OriginalWidth = 185
      OriginalHeight = 200
    end
    object dxVertContainerDockSite1: TdxVertContainerDockSite
      Left = 0
      Top = 0
      Width = 185
      Height = 609
      ActiveChildIndex = -1
      AllowFloating = True
      AutoHide = False
      CustomCaptionButtons.Buttons = <>
      DockingType = 0
      OriginalWidth = 185
      OriginalHeight = 140
      object dxDockPanel1: TdxDockPanel
        Left = 0
        Top = 0
        Width = 185
        Height = 256
        Color = clBtnFace
        ManagerColor = False
        AllowFloating = True
        AutoHide = False
        Caption = 'dxDockPanel1'
        CustomCaptionButtons.Buttons = <>
        TabsProperties.CustomButtons.Buttons = <>
        DockingType = 2
        OriginalWidth = 185
        OriginalHeight = 256
      end
      object dxDockPanel2: TdxDockPanel
        Left = 0
        Top = 256
        Width = 185
        Height = 353
        AllowFloating = True
        AutoHide = False
        Caption = 'dxDockPanel2'
        CustomCaptionButtons.Buttons = <>
        TabsProperties.CustomButtons.Buttons = <>
        ExplicitTop = 272
        DockingType = 2
        OriginalWidth = 185
        OriginalHeight = 353
      end
    end
  end
end
